version: '3.3'
services:
  forum:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: forum
      # So you don't have to use root, but you can if you like
      MYSQL_USER: saten
      # You can use whatever password you like
      MYSQL_PASSWORD: password
      # Password for root access
      MYSQL_ROOT_PASSWORD: SatenH!
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - 3307:3306
